### ISSUE TITLE
User-friendly Installer

### ISSUE THREAD

**Issue by leo60228** [EverestAPI/Everest#15]
`mod.sh`/`mod.bat` is confusing. Ideas:

* Linux-first script: Write a fully-featured bash script, and either embed MinGW's bash or find some other way of running it on Windows
  * Benefits: bash is featureful, and lends well to this sort of thing
  * Cons: It's Linux-first, and both developers and users will generally be running Windows
* Windows-first script: Write a fully-featured Powershell script, and require Linux users to install Powershell 6/Core (is there a difference?)
  * Benefits: Powershell is similar to C#, and can interface directly with C# code via `Add-Type`
  * Cons: It's Windows-first, and requires installing a somewhat heavy program on Linux just to run it, even though this shouldn't be necessary
* `.msi` Installer: Write an `.msi` script to install Everest
  * Benefits: ...it can be installed easily in an enterprise environment?
  * Cons: This is a horrible idea.
* scriptcs script: This might be the best idea; write "native" C# and wrap it in a `.bat`/`.sh` for ease of running. The script would automatically find Celeste, run MonoMod on it, in a nice, user-friendly package. It could even offer to install some "sample" mods.
  * Benefits: Code is normal C#, and we can do everything normal C# can.
  * Cons: Depends on scriptcs.
* Normal C# program: The same as scriptcs, but a normal, MSBuild-based program
  * Benefits: Same as scriptcs, plus the fact that it's a normal program from the user's perspective
  * Cons: Requires a full build chain, and doesn't get nice scripting built-ins

**Comment by 0x0ade** [comment]
I'd like to propose another option:

- Cross-platform GUI installer with headless mode: Easiest to use by casual users. Would consist of C# code.
  - Benefits: Same as normal C# program, plus the fact that the end user can literally download the installer .exe and run it.
  - Cons: Most effort. WinForms is no longer available on macOS.

Example: FEZMod.Installer and ETGMod.Installer, which I've worked on in the past.

![image](https://user-images.githubusercontent.com/1200380/36352754-244b1cee-14be-11e8-9a93-702ce49d4568.png)

![image](https://user-images.githubusercontent.com/1200380/36352656-8a172f1a-14bc-11e8-820e-90c70a4fb5d2.png)

Zatherz from the Mod the Gungeon team is currently rewriting the installer - including a headless installer. We could team up and reuse the same codebase for both of our installers, or completely start anew.

**Comment by 0x0ade** [comment]
I'll start working on "MiniInstaller" tomorrow, which is a headless installer to be used by the in-game updater... and as a temporary solution for this problem.

We should still create an user-friendly GUI installer in the foreseeable future.

**Comment by 0x0ade** [comment]
Just finished MiniInstaller - the code is relatively messy (everything stuffed into a single linear method), but it now serves as a temporary `mod.bat` / `mod.sh` replacement and as a critical part of the in-game updater.

I'd like to keep this issue open until we get around to creating a **user-friendly** (preferably GUI) installer.

**Comment by 0x0ade** [comment]
We've now got an user-friendly installer for Windows users and a less-user-friendly-but-still-easy-to-use installer for Linux and macOS.

https://twitter.com/everestapi/status/987078324672491521
