### ISSUE TITLE
Add dev-facing documentation

### ISSUE THREAD

**Issue by leo60228** [EverestAPI/Everest#16]
Currently, most of the codebase has XML comments (this is a good thing!). However, most of it is only relevant to people working on Everest, and not people working on mods. Based on past experience, I'd recommend DocFX, but you could go with whatever you want. (BTW, I thought I saw that DocFX requires VS2017, but I can't find that anymore)

**Comment by 0x0ade** [comment]
I've attempted to document most of the outward-facing Everest API with XML comments, omitting `<param>` and `<return>` where they wouldn't add much value other than reciting what `<summary>` already says.

https://github.com/EverestAPI/Everest/commit/51f508e80a120faa01941f6f8bd17a5fb85bb229

The commit also includes a few minor API changes, f.e. renaming `AssetMetadata` to `ModAsset` and `MTextureOverlay` to `MTextureOverride`.

The meta class properties (and thus the "meta formats") haven't been documented yet, though.

**Comment by 0x0ade** [comment]
I've just set up a DocFX project and pushed the contents of `_site` to the `gh-pages` branch: https://everestapi.github.io/Everest

In the future, when we've got a website, we should push the contents of `_site` to the `docs` subdirectory instead.

**Comment by leo60228** [comment]
There's a support forum now; might be able to close this soon!

**Comment by 0x0ade** [comment]
We've got a forum, tutorials, basic documentation for almost everything we're exposing and are available for support on Discord. I'm going to close this already, unless you notice that something critical is still missing / unfinished.
