### ISSUE TITLE
Suggest native support for decal placements on arbitrary layers

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/Everest#163]
So that we don't have to argue with what's in front of or behind something based on ID, we ought to have the ability to decide which layer a decal is on with some level of granularity. Placing a bg decal or fg decal without the depth definition would simply default their position to their current depths.

**Comment by maddie480** [comment]
The `depth` attribute on the decal registry is pretty close to this, but changes the depth of all decals sharing a same image.

**Comment by coloursofnoise** [comment]
The DecalRegistry attribute seems to be sufficient, I haven't seen any requests for depth support for individual decals since this issue was opened.
