### ISSUE TITLE
Minor map screen inconsistencies

### ISSUE THREAD

**Issue by Flamecrafter113** [EverestAPI/Everest#165]
The map screen is not as consistent with modded campaigns as it is the vanilla campaign. I have noticed two inconsistencies.
- The "scarf" under the chapter icon does not have any sort of "go up" movement for modded maps. This applies to both selecting an area or scrolling through campaigns.
- The icons of the vanilla campaign move one after another, while modded campaigns move all at once.

These minor issues do not change much, just minor nitpicks.

**Comment by coloursofnoise** [comment]
Both of these seem to be caused by checks added in https://github.com/EverestAPI/Everest/commit/6b2d7002c28cb7a8749d996e5144cec34c47d218

I don't know what the menu storage issue is referring to, so I don't know if these checks are still needed.

**Comment by coloursofnoise** [comment]
> The map changes were introduced way before the commit [posted above], but for all chapters. That commit just adds the checks to revert it to vanilla for vanilla, but the actual changes have been there much earlier. They're in part there because switching between levelsets took ages with the vanilla animations, and we can't remove the tweak anymore unless [we] want to break TASes **and** make the animation horribly slow again.

\- 0x0ade
