### ISSUE TITLE
Vanilla Debug bug: sending [space] as a command crashes Celeste w/ OverflowException

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/Everest#167]
https://pastebin.com/BZnuQ2qH

Low priority, of course, being avoidable in a lot of scenarios, but it did catch a casual player checking hitboxes just now.

(is this even in our power to fix?)

**Comment by DashingCat** [comment]
Here is the relevant code in Monocle (source : https://bitbucket.org/MattThorson/monocle-engine/src/85205ffbfe927b41f5dfe85fdb3f09f42770ff1a/Monocle/Util/Commands.cs#lines-387:400)

```c#
private void EnterCommand()
{
    string[] data = currentText.Split(new char[] { ' ', ',' }, StringSplitOptions.RemoveEmptyEntries);
    if (commandHistory.Count == 0 || commandHistory[0] != currentText)
        commandHistory.Insert(0, currentText);
    drawCommands.Insert(0, new Line(currentText, Color.Aqua));
    currentText = "";
    seekIndex = -1;

    string[] args = new string[data.Length - 1];
    for (int i = 1; i < data.Length; i++)
        args[i - 1] = data[i];
    ExecuteCommand(data[0].ToLower(), args);
}
```

Monocle extracts the different parts of the command by splitting on `,` and ` `, but it never checks that the command may not actually contain any valid part, leading to the overflow exception on the `args` array allocation.

I made a pull request (#168) that adds a check before calling the actual `EnterCommand` method to avoid this issue.
