### ISSUE TITLE
Mod repository/installer

### ISSUE THREAD

**Issue by leo60228** [EverestAPI/Everest#17]
Right now, the source for mods is to go on the Discord and ask for WIPs. *Almost* anything would be better than this for users.

**Comment by 0x0ade** [comment]
I'm proposing two possible repositories: 
- [modworkshop](https://modworkshop.net/) - I've cooperated with them in the past, they're nice people. Their community is mostly focused around Payday 2, though.
- [Nexus](https://www.nexusmods.com/) - more polished and they've got an installer, but I don't know if / how that will work with Everest.

**Comment by 0x0ade** [comment]
We're now on Nexus Mods: https://www.nexusmods.com/celeste/mods/1
