### ISSUE TITLE
Fail to install everst mod loader

### ISSUE THREAD

**Issue by Me132** [EverestAPI/Everest#176]
I have a free copie of celeste, Im trying to install everest mod loader but it fails in the last screen every time, the game itself runs fine, here is the miniistaller log

Loading Mono.Cecil
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\Mono.Cecil.dll
Loading Mono.Cecil.Mdb
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\Mono.Cecil.Mdb.dll
Loading Mono.Cecil.Pdb
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\Mono.Cecil.Pdb.dll
Loading MonoMod.Utils.dll
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\MonoMod.Utils.dll
Loading MonoMod
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\MonoMod.exe
Loading MonoMod.RuntimeDetour.dll
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\MonoMod.RuntimeDetour.dll
Loading MonoMod.RuntimeDetour.HookGen
Lazily loading C:\Games\Celeste v1.3.0.0-PiviGames.blog\MonoMod.RuntimeDetour.HookGen.exe
Running MonoMod for C:\Games\Celeste v1.3.0.0-PiviGames.blog\orig\Celeste.exe
MonoMod 20.5.2.5
[MonoMod] Reading input file into module.
[MonoMod] [ReadMod] Loading mod dir: C:\Games\Celeste v1.3.0.0-PiviGames.blog
[MonoMod] [ReadMod] Loading mod: C:\Games\Celeste v1.3.0.0-PiviGames.blog\Celeste.Mod.mm.dll
[MonoMod] [Main] Scanning for mods in directory.
[MonoMod] [ReadMod] Loading mod dir: C:\Games\Celeste v1.3.0.0-PiviGames.blog\orig
[MonoMod] [Main] mm.AutoPatch();
[MonoMod] [AutoPatch] Parsing rules in loaded mods
[MonoMod] [RulesModder] [Write] Writing modded module into output stream.
System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'MonoMod.MonoModRules'. ---> System.Exception: Unsupported version of Celeste: 1.3.0.0
   en MonoMod.MonoModRules..cctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   en MonoMod.InlineRT.MonoModRulesManager.ExecuteRules(MonoModder self, TypeDefinition orig)
   en MonoMod.MonoModder.ParseRules(ModuleDefinition mod)
   en MonoMod.MonoModder.AutoPatch()
   en MonoMod.Program.Main(String[] args)

System.Exception: MonoMod failed creating a patched assembly!
   en MiniInstaller.Program.RunMonoMod(String asmFrom, String asmTo)
   en MiniInstaller.Program.Main(String[] args)

Installing Everest failed.
Please create a new issue on GitHub @ https://github.com/EverestAPI/Everest
or join the #modding_help channel on Discord (invite in the repo).
Make sure to upload your miniinstaller-log.txt

**Comment by PenguinOwl** [comment]
> Free copie of celeste

I really hope this means that you were gifted the game or got it for free in the Epic giveaway period.
If so, you need to update. Everest is currently built for `v1.3.1.2`, you are running on `v1.3.0.0`.

**Comment by Me132** [comment]
I'm sorry for being unable to legally buy a copie, I just wanna play a game
that I love, if somehow makes your feel better, or for some reason so you
even care, I will find a way to buy it. Thanks for your time

**Comment by 0x0ade** [comment]
No need to be sorry. We've all been there, done that.

All you need to do is to find an up to date version of Celeste. As I've said, that's the only thing that matters here. I don't care where you'll get that updated Celeste from, as long as you don't hurt the devs. Piracy is still better than key reselling, after all.

**Comment by Me132** [comment]
I actually did find the latest version and try it, find weird either, I'm
not gonna keep trying, I just wanna play so I'll buy it
