### ISSUE TITLE
LightingRenderer related crashes on map reload

### ISSUE THREAD

**Issue by max4805** [EverestAPI/Everest#178]
Some mappers reported random crashes on map reload (after saving in Ahorn):

https://hatebin.com/cwbtmoqzss

https://cdn.discordapp.com/attachments/514006912115802113/714618373924847686/error_log.txt

This seems to be a "random hard-to-reproduce" crash as I wasn't able to replicate myself, but that has been reported multiple times.

**Comment by maddie480** [comment]
Tried to fix that through https://github.com/EverestAPI/Everest/commit/10d0eb62ac84b3d3c76fb1d0719c1c416d5dccf0 and https://github.com/EverestAPI/Everest/commit/2582eafdd559b5063f8cea8feb2c370f2959d5ad, and did not hear back from it since then. 😅
