### ISSUE TITLE
Better map documentation

### ISSUE THREAD

**Issue by leo60228** [EverestAPI/Everest#18]
This is more of a problem for @Vexatos and Cruor, but as most people will be using Everest for custom maps, this is definitely a spot that needs work. Despite the fact that this is more of a problem for Maple and whoever is working on the one or more GUIs, this should happen before 1.0 is out if we want it to actually be useful.

**Comment by 0x0ade** [comment]
Additionally, we should add documentation about the meta formats (not restricted to map metadata). Right now, the only "documentation" for the MapMeta format is in form of an /ideas/ post on my website: https://0x0ade.github.io/ideas/def-everest-mapmeta

**Comment by leo60228** [comment]
Closing, the modstruct tutorial and, y'know, Ahorn kinda solves this. Ahorn's README could use some work, but that's a problem for them.
