### ISSUE TITLE
Custom Dash Block Debris

### ISSUE THREAD

**Issue by asdfsdfadfasfasd** [EverestAPI/Everest#188]
Please bestow upon tileset xml an option that determines the tiletype of the debris that is emitted when a custom tileset dash block falls into pieces.
Sincerely, the fish of the tank

**Comment by asdfsdfadfasfasd** [comment]
Case closed.
For anyone wondering how to do this, make a .png with the same name as your tileset id, and put it in Graphics->Atlases->Gameplay->debris. Thanks to coloursofnoise.

**Comment by max4805** [comment]
This isn't really a solution to the problem, since tileset IDs are unique **per map**, and this solution affects debris **in all maps**...
