### ISSUE TITLE
Problem installing Everest

### ISSUE THREAD

**Issue by cupofbutter** [EverestAPI/Everest#216]
[installer-log.txt](https://github.com/EverestAPI/Everest/files/4974121/installer-log.txt)

I'm not sure what's wrong here.

Thank you in advance!

**Comment by maddie480** [comment]
Did you run Celeste at least once? If not, try running it (it should install XNA on first launch) then try installing Everest again.

**Comment by maddie480** [comment]
Closing since this got no update for a month.
