### ISSUE TITLE
Running C-side opens B-side instead

### ISSUE THREAD

**Issue by monroth** [EverestAPI/Everest#228]
If your map don't have hearts in B-side, than it is possible to unlock C-side without unlocking B-side, because in general you can gather heart of A-side without gathering cassette.
However, If in that case you try to run that C-side, it will run B-side instead.
Reproduced in that minimal mod
[Testmod.zip](https://github.com/EverestAPI/Everest/files/5144779/Testmod.zip)

**Comment by maddie480** [comment]
Displayed stats also are from the B-side, despite saying "C-side" with the C-side logo.
