### ISSUE TITLE
When I tried to open the map I designed, it crashed. (I tried to clean [deleted] all my mods before)

### ISSUE THREAD

**Issue by OneGamerr** [EverestAPI/Everest#297]
Hello.
I was using Ahorn to make maps. I basically grab the objects from the Placements tab on the right. One day I cleaned up all the mods in Olympus. Then I found that my whole game can no longer start running. 
Later, I re-downloaded all mods as much as possible. Now I can enter the game. But when I click on my map, the game crashes and left a long error report. 

[errorLog.txt](https://github.com/EverestAPI/Everest/files/6333090/errorLog.txt)

(All my mods, if need)
![AAAA](https://user-images.githubusercontent.com/82791224/115178390-10a14b80-a086-11eb-9482-b5f823eae2cd.PNG)

**Comment by maddie480** [comment]
Your map seems to use a styleground you don't have installed anymore, check if that's the case.

**Comment by OneGamerr** [comment]
omg, it worked, thanks!
