### ISSUE TITLE
Remove FNADroid code

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#310]
[FNADroid](https://github.com/0x0ade/FNADroid) is not properly supported/not used and related code should be removed from Everest.
Examples: [Everest.Flags.cs](https://github.com/EverestAPI/Everest/blob/0d098aab868084d5b5fc649fd15a35edd6e21557/Celeste.Mod.mm/Mod/Everest/Everest.Flags.cs), [CoreModule.cs](https://github.com/EverestAPI/Everest/blob/0d098aab868084d5b5fc649fd15a35edd6e21557/Celeste.Mod.mm/Mod/Core/CoreModule.cs#L79-L82), everything in [Touch/](https://github.com/EverestAPI/Everest/tree/dev/Celeste.Mod.mm/Mod/Touch)

**Comment by xaviershrier** [comment]
*boop*
