### ISSUE TITLE
Add Fallback SoundSurfaceIndex for Tile Entities

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#311]
`SurfaceIndex.TileToIndex[tile]` crashes with a KeyNotFound exception when given a tileset without a sound attribute.
This could be fixed by providing a default sound id (`0`) to all tilesets missing a sound attribute.
Relevant code: [Patches/Autotiler.cs](https://github.com/EverestAPI/Everest/blob/0d098aab868084d5b5fc649fd15a35edd6e21557/Celeste.Mod.mm/Patches/Autotiler.cs#L72-L74)

Additionally, I noticed that IntroCrushers do not respect tileset sounds properly, which could be added in [Patches/IntroCrusher.cs](https://github.com/EverestAPI/Everest/blob/0d098aab868084d5b5fc649fd15a35edd6e21557/Celeste.Mod.mm/Patches/IntroCrusher.cs#L35-L52)

**Comment by grian32** [comment]
I'd like to take this ^^
