### ISSUE TITLE
Apply DecalRegistry tags to multiple Decals

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#315]
Allow a single set of [DecalRegistry](https://github.com/EverestAPI/Everest/blob/dev/Celeste.Mod.mm/Mod/Registry/DecalRegistry.cs) properties to be applied to multiple decals in the following ways:
- Ending the `path` attribute with a `/` will cause it to be treated as a folder, and all decals in the folder will be affected
- Ending the `path` attribute with a `*` will act as a wildcard, and match all decals that begin with that path

**Comment by catapillie** [comment]
I would like to work on this
