### ISSUE TITLE
Overload Chooser<T> equality operator

### ISSUE THREAD

**Issue by vivianlonging** [EverestAPI/Everest#333]
Currently it's a massive hassle to compare two Chooser<T> together, so my thought process is just make an overload in Choice and overload in Chooser such that it compares by values as opposed to references.

the less efficient but "simple" explanation is
```csharp
Choice<T> a == Choice<T> b
return a.Value == b.Value && a.Weight == b.Weight;

Chooser<T> a == Chooser<T> b
foreach(Choice c in a.choices)
{
   if(!b.choices.Contains(c)) return false;
}
return true;
```

**Comment by coloursofnoise** [comment]
Resolved by making Chooser.Choice public - ee0b4a4f1c4b12b0db46100d9389f2e04ec5c152
