### ISSUE TITLE
Taking a Red Booster diagonally up through room transition redirects to straight up

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#343]
This is unintuitive behaviour that cannot occur in vanilla.

Potentially breaking if this is used as an intentional mechanic in a modded map.

**Comment by WEGFan** [comment]
It's because the game sets the player horizontal speed to 0 in `Player.BeforeUpTransition()`, so the booster speed changes from `(169.71, -169.71)` to `(0, -169.71)`, and rounds to `(0, -170)` after transition. It is also slower than normal booster that going up which is `(0, -240)`.
