### ISSUE TITLE
Russian language bugging the "Mod options" menu

### ISSUE THREAD

**Issue by PhoenixXL-tech** [EverestAPI/Everest#376]
So this happens only on russian language on latest everest version (3070)
idk this never happen before 3070
![image](https://user-images.githubusercontent.com/74854460/133603074-757b17b1-c47c-4e50-820b-bd7eae0664f1.png)
![image](https://user-images.githubusercontent.com/74854460/133603114-fe11913e-2878-412a-b5a6-46ea71647e69.png)

**Comment by WEGFan** [comment]
It seems that there are some useless comments causing the text being too long, but they existed when the translation first came out...

Maybe you can also go through the menu and see if there's any mod has long text that makes the menu off screen, and report them to mod devs.

**Comment by WEGFan** [comment]
Just pushed a fix that removed the comments in 3075, hope it can reduce the menu width a bit

**Comment by PhoenixXL-tech** [comment]
> It seems that there are some useless comments causing the text being too long, but they existed when the translation first came out...
> 
> Maybe you can also go through the menu and see if there's any mod has long text that makes the menu off screen, and report them to mod devs.

nope, seems it's only because comment on FMOD live update

**Comment by WEGFan** [comment]
Closing the issue as it's fixed in Everest 3075 (hopefully one day I can have an implementation on forcing menus don't go off screen...)

![](https://user-images.githubusercontent.com/7558201/134004767-6011b099-f715-44d5-b979-2d152ae54483.png)
