### ISSUE TITLE
mistakes in Russian translation

### ISSUE THREAD

**Issue by PhoenixXL-tech** [EverestAPI/Everest#382]
So... When Russian language come I saw that translation have some mistakes and I want to make it correct. How can I do that?
![23-26-18-134004767-6011b099-f715-44d5-b979-2d152ae54483.png](https://user-images.githubusercontent.com/74854460/134783921-c370af58-e28d-4db3-bff1-a1cf1db36d1b.png)

**Comment by coloursofnoise** [comment]
Create a Pull Request with modifications to the [Russian.txt](https://github.com/EverestAPI/Everest/blob/dev/Celeste.Mod.mm/Content/Dialog/Russian.txt) file

**Comment by PhoenixXL-tech** [comment]
done.

**Comment by WEGFan** [comment]
You can also copy the dialogs from English.txt if you want to translate currently missing texts in Russian

**Comment by PhoenixXL-tech** [comment]
done. check pull requests.
