### ISSUE TITLE
Console command DebugRC endpoint

### ISSUE THREAD

**Issue by Kataiser** [EverestAPI/Everest#390]
Small feature request, I'd like to send commands to the game plz (URL encoded cause spaces and such)

**Comment by WEGFan** [comment]
I currently don't have a good idea of returning commands output to the endpoint (not sure if you want it), but only adding send commands feature should be easy to do.

**Comment by Kataiser** [comment]
Returning output isn't required for what I have in mind, but it's probably a good idea to have it if possible

**Comment by Kataiser** [comment]
I have no idea what I was trying to do when I suggested this, rip
