### ISSUE TITLE
Expose the "Rename" option on File Select for already existing saves

### ISSUE THREAD

**Issue by xaviershrier** [EverestAPI/Everest#392]
What it says on the tin, currently this option only exists when creating a new files, and this should be changed to work for all files so players can rename ones they've already created easily.

**Comment by WEGFan** [comment]
If a player creates a new save named Alex, Theo's sister's name will become Maddy to avoid conflict, so should we also change it when renaming savefile?

**Comment by xaviershrier** [comment]
Yes, since otherwise you would subvert that system and it would be weird
