### ISSUE TITLE
Proxy server for Everest's in-game mod download

### ISSUE THREAD

**Issue by Pioooooo** [EverestAPI/Everest#394]
Since the currently used [host](https://max480-random-stuff.appspot.com/celeste/everest_update.yaml) of `everest_update.yaml` is blocked by China mainland (Google Stuff), I cannot use the in-game mod download feature without a system proxy. Thus a customized proxy server would be appreciated.

**Comment by WEGFan** [comment]
I have already built one on my server and you only need to install a mod, it's currently in alpha now and I don't want to send the file here publicly, can I have your contact (Discord / QQ / email) so I can DM you?

**Comment by Pioooooo** [comment]
Ah just add my QQ *[REDACTED]* plz. Thanks a lot.
