### ISSUE TITLE
Mininstaller crashes when installing everest

### ISSUE THREAD

**Issue by anzakitty** [EverestAPI/Everest#421]
[log-sharp.txt](https://github.com/EverestAPI/Everest/files/8106209/log-sharp.txt)
Whenever i try to install everest, this happens. I've tried other installations and nothing has worked.

**Comment by coloursofnoise** [comment]
Make sure to run Celeste at least once before installing Everest, if that doesn't work you can switch to the OpenGL beta in Steam.

**Comment by anzakitty** [comment]
thanks, that actually worked!
