### ISSUE TITLE
live code reloading crashes the game on linux

### ISSUE THREAD

**Issue by microlith57** [EverestAPI/Everest#428]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

when i rebuild a mod dll, everest tries to unload the previous version, but crashes when doing so.

### Steps to reproduce

1.  install Everest `3282-azure-27da1` (i used the itch.io version of celeste) with `CodeReload_WIP: true` set
2.	clone https://github.com/microlith57/LiveReloadTestMod into the mods folder
3.	change `src/LiveReloadTestModModule.cs` so that line 23 is uncommented and line 25 is commented
4.	build the mod, launch Celeste, and verify that dashing launches you upwards
5.	revert the change and rebuild
6.  observe that the game crashes with a `System.BadImageFormatException`

### Expected behavior

i expected the game not to crash, and the `On` hook to be unloaded and reloaded with the new code

### Operating System

Ubuntu 20.04.4 LTS

### Everest Version

3282

### Mods required to reproduce

- https://github.com/microlith57/LiveReloadTestMod, made for this issue

### Additional context

relevant logs are in the https://github.com/microlith57/LiveReloadTestMod repository

**Comment by DemoJameson** [comment]
is this fixed in core everest?

**Comment by microlith57** [comment]
seems to be!
