### ISSUE TITLE
Installer window cropped/scaled oddly

### ISSUE THREAD

**Issue by NeloBlivion** [EverestAPI/Everest#53]
When opening the installer, it seems to be cropped/scaled weirdly, so the full window cannot be viewed. As such, I am unable to install Everest.
![ey7w5YhTsV](https://user-images.githubusercontent.com/41271523/65987230-53d4a300-e47d-11e9-8504-ce8c3044d975.jpg)
My display is 1920x1080 with 125% scaling in Windows' Settings. I'm assuming it's something to do with that but I'm not sure. Any way to fix this? I've already tried changing the compatibility settings, but to no avail.

**Comment by orbittwz** [comment]
Well yeah, the scaling should be 100%
In Windows 10, go to Display settings and change back to 100% scaling
![image](https://user-images.githubusercontent.com/45605734/66287888-03779e00-e8e0-11e9-8fe1-6b6aa50a9546.png)

**Comment by 0x0ade** [comment]
Resetting the display scale is just a workaround, not a proper fix.

Unfortunately I've been unable to replicate it on my PC, which means that I can't fix it for now either.

**Comment by 0x0ade** [comment]
Fixed with the release of Olympus. https://everestapi.github.io/#installing-everest
