### ISSUE TITLE
Feature Request: meta.yaml variable to allow Core Heart to be shown on overworld

### ISSUE THREAD

**Issue by Vawlpe** [EverestAPI/Everest#54]
The core heart being visible is hardcoded to the level ID 9 (core) unlike how you can use State 3 to view the moon, I am unfamiliar with celeste and Everest code so IDK how to make this possible myself...

**Comment by Vawlpe** [comment]
Fuck it imma re-learn C#

**Comment by 0x0ade** [comment]
Enough people have asked for this to become a feature in Everest. Dunno if I'll ever get to do it myself, but if anyone wants to submit a PR for this, feel free to do so.

**Comment by Vawlpe** [comment]
I'm p sure someone made a codemod for this already so if there's an easy way to integrate that in somehow that'd be nice

**Comment by Vawlpe** [comment]
Yep, I think this is the map that codemod was made for lol
https://gamebanana.com/maps/204792

**Comment by orbittwz** [comment]
Hi!
I can share the code for this to happen, but it's not generic, thus only works with my campaign SID...
Though I can think of another workaround, maybe to detect which chapter is a core chapter by type of setting/feature:
1. the area icon
2. the music track (THE MAIN ONE set in Audio meta)
3. starting inventory
4. mountain position in the overworld
and so on...
let me know :)

**Comment by Vawlpe** [comment]
> I can share the code for this to happen, but it's not generic, thus only works with my campaign SID...
Yes, that would probably be helpful @orbittwz 

Apparently reading code in a language you haven't used in 5 years is exceptionally though so I'm having no luck with this :\

**Comment by orbittwz** [comment]
`        private void MountainRenderer_Update(On.Celeste.MountainRenderer.orig_Update orig, MountainRenderer self, Monocle.Scene scene)
        {
            bool flag = self.Area == AreaData.Get("orbittwz/blueoceanfloor/2-millennium").ID;
            var areaProp = self.GetType().GetProperty("Area", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
            if (flag)
            {
                int currentId = (int)areaProp.GetValue(self);
                areaProp.SetValue(self, 9);
                orig(self, scene);
                areaProp.SetValue(self, currentId);
            }
            else orig(self, scene);
        }`

Sure, there...

**Comment by orbittwz** [comment]
Sure, there...

>         private void MountainRenderer_Update(On.Celeste.MountainRenderer.orig_Update orig, MountainRenderer self, Monocle.Scene scene)
        {
            bool flag = self.Area == AreaData.Get("orbittwz/blueoceanfloor/2-millennium").ID;
            var areaProp = self.GetType().GetProperty("Area", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
            if (flag)
            {
                int currentId = (int)areaProp.GetValue(self);
                areaProp.SetValue(self, 9);
                orig(self, scene);
                areaProp.SetValue(self, currentId);
            }
            else orig(self, scene);
        }

>

**Comment by orbittwz** [comment]
Sure, there...

[code.txt](https://github.com/EverestAPI/Everest/files/3695682/code.txt)

**Comment by Vawlpe** [comment]
Thx~ uwu, I'm gonna try n look trough it and figure this out...
if i cant get it to work I'll PR it lol.

Edit: Looking back on this the change was very simple I just didn't have a grasp of the EverestAPI code base at the time :sweat_smile:

**Comment by 0x0ade** [comment]
Fixed with https://github.com/EverestAPI/Everest/commit/7dd43f5a7aea389996deafe8df2601037dc9509d
