### ISSUE TITLE
using Debug map in ANY save, causing losing B/C sides MapMetaModeProperties

### ISSUE THREAD

**Issue by orbittwz** [EverestAPI/Everest#55]
as discussed before in the channel...
I discovered it when playtesting my maps which have a special Starting Room setting.
I used the debug map, teleported to a room, and finished the A side from set room...
Entered B/C sides from the beginning, the spawn point was wrong, and was set to the room which was closest to 0,0 and not my Starting Room meta value.
FYI

**Comment by 0x0ade** [comment]
Fixed with #56.
