### ISSUE TITLE
Desync on macOS due to floating point rounding in DreamBlock.Setup

### ISSUE THREAD

**Issue by swoolcock** [EverestAPI/Everest#556]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

The code in `DreamBlock.Setup()` that calculates the desired number of dream block particles has inconsistent rounding errors between macOS and Windows.  Untested on Linux but I assume this is a Mono issue rather than specifically macOS, so the issue likely exists there too.

The calculation is `(int)(width / 8f * (height / 8f * 0.7f))`.  With a width and height of 120x32, this results in 42 particles on macOS and 41 on Windows.  Performing the calculation with doubles gives 42 on both platforms.

Due to this inconsistency, a different number of random samples are taken, causing a TAS desync in certain places.  One example is Farewell `j-08`.  The change in the random sequence causes the `CrumbleWallOnRumble` entities to break in a different order such that the TAS no longer gets a corner boost into the next screen.

After some discussion in Celestecord, one potential solution is to subtract a small value (say 0.0001f) before truncating to int, which in this case will result in 41 particles on both platforms.  I'm willing to implement and test this on both Windows and macOS.

Note that this is a bug in vanilla, not Everest.

### Steps to reproduce

Run 9.tas and skip to j-08 (Reconciliation).
Note that Madeline does not a proper corner boost at the end of the room and thus dies to lightning in the next room.

Test code that simulates the 120x32 dream block (running in module Load):
```cs
float width = 120f;
float height = 32f;
int floatValue = (int) (width / 8f * (height / 8f * 0.7f));
int doubleValue = (int) (width / 8.0 * (height / 8.0 * 0.7));
int adjustedFloatValue = (int) (width / 8f * (height / 8f * 0.7f) - 0.0001f);
Logger.Log(LogLevel.Error, nameof(SortFixModule), $"(float) 120f/8f * (32f/8f * 0.7f) = {floatValue}");
Logger.Log(LogLevel.Error, nameof(SortFixModule), $"(double) 120f/8.0 * (32f/8.0 * 0.7) = {doubleValue}");
Logger.Log(LogLevel.Error, nameof(SortFixModule), $"(adjusted float) 120f/8f * (32f/8f * 0.7f) - 0.0001f = {adjustedFloatValue}");
```

macOS:
```
(11/30/2022 20:43:02) [Everest] [Error] [SortFixModule] (float) 120f/8f * (32f/8f * 0.7f) = 42
(11/30/2022 20:43:02) [Everest] [Error] [SortFixModule] (double) 120f/8.0 * (32f/8.0 * 0.7) = 42
(11/30/2022 20:43:02) [Everest] [Error] [SortFixModule] (adjusted float) 120f/8.0 * (32f/8.0 * 0.7) - 0.0001f = 41
```

Windows:
```
(11/30/2022 20:44:33) [Everest] [Error] [SortFixModule] (float) 120f/8f * (32f/8f * 0.7f) = 41
(11/30/2022 20:44:33) [Everest] [Error] [SortFixModule] (double) 120f/8.0 * (32f/8.0 * 0.7) = 42
(11/30/2022 20:43:02) [Everest] [Error] [SortFixModule] (adjusted float) 120f/8.0 * (32f/8.0 * 0.7) - 0.0001f = 41
```

### Expected behavior

Blocks break in the correct order and Madeline does not die in the next room.

### Operating System

macOS and Windows 10

### Everest Version

3650

### Mods required to reproduce

CelesteTAS and 9.tas if you want to test desync, but the issue exists with no mods and can be seen just based on the different autotiling of the blocks at the end of the room.

**Comment by DemoJameson** [comment]
Fixed in core everest
