### ISSUE TITLE
MacOS manual installation is trying to find a .exe file

### ISSUE THREAD

**Issue by poachedegg12** [EverestAPI/Everest#589]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

When trying to install Everest using mono, the terminal gives an error saying it can't find celeste.exe, even though it's a MacOS program and there is no exe file included in the directory. Any help with this would be much appreciated.

### Steps to reproduce

1. Install mono
2. cd to the MacOS folder in the Celeste folder
3. Move the main.zip contents to the folder
4. run mono MiniInstaller.exe
5. Profit

### Expected behavior

It would install Everest

### Operating System

MacOS 13.2 Ventura

### Everest Version

Latest

**Comment by maddie480** [comment]
The macOS version does have an exe file as well, but it is in `Contents/Resources`. You should do the installation steps there. The website mentions `Contents/MacOS` but that's outdated 😅

**Comment by poachedegg12** [comment]
> The macOS version does have an exe file as well, but it is in `Contents/Resources`. You should do the installation steps there. The website mentions `Contents/MacOS` but that's outdated 😅

Thanks for that, I hope they update the website eventually.
