### ISSUE TITLE
Add custom keybinds for the slight camera panning on the map while a level is selected.

### ISSUE THREAD

**Issue by AdoHTQ** [EverestAPI/Everest#597]
### I am planning on implementing this myself

Yes

### Describe your request

![image](https://user-images.githubusercontent.com/19363927/224935185-af70fc35-f6fe-4080-bf44-c35b28587eb3.png)

The slight camera rotation on the mountain view is hard-coded to use the WASD key-binds as shown in the image above. This can get annoying if your menu key-binds contain WASD.

This could be fixed by setting these keys to be what you set your debug camera movement keys to in the mod settings key/controller config. An option could also be added to completely disable this movement as it feels unnecessary but this may be better suited for a separate mod.

### Additional context

I'm going to develop a code-mod that adds the same functionality, but it should probably be added into base Everest as well.

**Comment by FenyLabs** [comment]
Also applies to debug 3d camera movement and clear screen panning I believe

**Comment by AdoHTQ** [comment]
Yes, I think it should apply to clear screen panning. Debug 3d camera movement already had customizable keybinds in everest and they are what I used to determine the other ones.

**Comment by swoolcock** [comment]
@AdoHTQ any update on this?  I'd like to use `MountainAim` for looking around the map in CU2 lobby maps if possible.  Making it customisable should absolutely be in Everest.

**Comment by AdoHTQ** [comment]
I created a PR with the fixed changes. No idea if it's going to be merged. You can compile my branch if you really need the modifications.

I also don't know if the CU2 lobby map uses the MountainAim controls but if it does then it should work with my changes.
