### ISSUE TITLE
theo crystals don't prevent up-transitions while not held

### ISSUE THREAD

**Issue by microlith57** [EverestAPI/Everest#644]
### describe the bug

currently, theo crystals block right-transitions when not held, but not up-transitions.
when transitioning upwards while there is an unheld theo crystal in the room, it dies because it is below the current room's bounds; this kills the player, and crashes the game with a nullref (because the transition expects the player to be non-null).
with assist mode invincibility, instead of crashing this teleports the theo crystal upwards into the new room.

### steps to reproduce

1. place two rooms vertically above each other, with a spawnpoint in each, and a theo crystal in the lower one
2. transition from the lower room to the upper one while the crystal is not being held

### expected behavior

instead of crashing or teleporting the crystal, the player should simply bonk off the transition, similarly to a right-transition under the same circumstances.

**Comment by nhruo123** [comment]
Not sure if its smart to bonk off the player like in a right-transition, I have played around with it and its a completely different feel then bonk-ing against a block especially when ducked.
And what about Theo itself currently if you throw him at the ceiling he will bounce off it unlike right transitions which in them he passes to the next room.
