### ISSUE TITLE
i can't reinstall everest 

### ISSUE THREAD

**Issue by yui-shiba** [EverestAPI/Everest#645]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

No

### Describe the bug

So i unitall olympus one time and when i try to install again it open but goes to a black screen, when i tried to install everest directly but shows a txt file

### Steps to reproduce

1. install everest
2. desinstall everest
3. try to install everest again

### Expected behavior

olympus will open but will be a black screen

### Operating System

Windows 11

### Everest Version

4057

### Additional context

Everest.Installer v19.9.0.33802
Starting installation
Installing: 4057 (core)
To: E:\SteamLibrary\steamapps\common\Celeste
STEP: BACKUP @ E:\SteamLibrary\steamapps\common\Celeste
Celeste.exe -> orig\Celeste.exe

STEP: DOWNLOAD & UNPACK
Downloading https://dev.azure.com/EverestAPI/Everest/_apis/build/builds/3357/artifacts?artifactName=main&api-version=5.0&%24format=zip
0 bytes
Downloaded 33609.00 KiB in 12.43 seconds.
Celeste-icon.png -> E:\SteamLibrary\steamapps\common\Celeste\Celeste-icon.png
Celeste.Mod.mm.deps.json -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.deps.json
Celeste.Mod.mm.dll -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.dll
Celeste.Mod.mm.pdb -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.pdb
Celeste.Mod.mm.xml -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.xml
Celeste.xml -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.xml
DiscordGameSDK.dll -> E:\SteamLibrary\steamapps\common\Celeste\DiscordGameSDK.dll
DiscordGameSDK.pdb -> E:\SteamLibrary\steamapps\common\Celeste\DiscordGameSDK.pdb
DotNetZip.dll -> E:\SteamLibrary\steamapps\common\Celeste\DotNetZip.dll
FNA.xml -> E:\SteamLibrary\steamapps\common\Celeste\FNA.xml
I18N.CJK.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.CJK.dll
I18N.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.dll
I18N.MidEast.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.MidEast.dll
I18N.Other.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.Other.dll
I18N.Rare.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.Rare.dll
I18N.West.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.West.dll
Jdenticon.dll -> E:\SteamLibrary\steamapps\common\Celeste\Jdenticon.dll
KeraLua.dll -> E:\SteamLibrary\steamapps\common\Celeste\KeraLua.dll
MAB.DotIgnore.dll -> E:\SteamLibrary\steamapps\common\Celeste\MAB.DotIgnore.dll
Microsoft.NET.HostModel.dll -> E:\SteamLibrary\steamapps\common\Celeste\Microsoft.NET.HostModel.dll
Microsoft.Win32.SystemEvents.dll -> E:\SteamLibrary\steamapps\common\Celeste\Microsoft.Win32.SystemEvents.dll
MiniInstaller-linux -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-linux
MiniInstaller-osx -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-osx
MiniInstaller-win.exe.manifest -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-win.exe.manifest
MiniInstaller-win.exe -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-win.exe
MiniInstaller-win64.exe -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-win64.exe
MiniInstaller.deps.json -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.deps.json
MiniInstaller.dll -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.dll
MiniInstaller.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.pdb
MiniInstaller.runtimeconfig.json -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.runtimeconfig.json
Mono.Cecil.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.dll
Mono.Cecil.Mdb.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.Mdb.dll
Mono.Cecil.Pdb.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.Pdb.dll
Mono.Cecil.Rocks.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.Rocks.dll
MonoMod.Backports.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Backports.dll
MonoMod.Backports.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Backports.pdb
MonoMod.Backports.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Backports.xml
MonoMod.Core.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Core.dll
MonoMod.Core.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Core.pdb
MonoMod.Core.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Core.xml
MonoMod.Iced.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Iced.dll
MonoMod.Iced.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Iced.pdb
MonoMod.Iced.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Iced.xml
MonoMod.ILHelpers.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.ILHelpers.dll
MonoMod.ILHelpers.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.ILHelpers.pdb
MonoMod.Patcher.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.dll
MonoMod.Patcher.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.pdb
MonoMod.Patcher.runtimeconfig.json -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.runtimeconfig.json
MonoMod.Patcher.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.xml
MonoMod.Patcher -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher
MonoMod.RuntimeDetour.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.dll
MonoMod.RuntimeDetour.HookGen.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.dll
MonoMod.RuntimeDetour.HookGen.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.pdb
MonoMod.RuntimeDetour.HookGen.runtimeconfig.json -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.runtimeconfig.json
MonoMod.RuntimeDetour.HookGen.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.xml
MonoMod.RuntimeDetour.HookGen -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen
MonoMod.RuntimeDetour.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.pdb
MonoMod.RuntimeDetour.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.xml
MonoMod.Utils.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Utils.dll
MonoMod.Utils.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Utils.pdb
MonoMod.Utils.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Utils.xml
NETCoreifier.deps.json -> E:\SteamLibrary\steamapps\common\Celeste\NETCoreifier.deps.json
NETCoreifier.dll -> E:\SteamLibrary\steamapps\common\Celeste\NETCoreifier.dll
NETCoreifier.pdb -> E:\SteamLibrary\steamapps\common\Celeste\NETCoreifier.pdb
Newtonsoft.Json.dll -> E:\SteamLibrary\steamapps\common\Celeste\Newtonsoft.Json.dll
NLua.dll -> E:\SteamLibrary\steamapps\common\Celeste\NLua.dll
NLua.pdb -> E:\SteamLibrary\steamapps\common\Celeste\NLua.pdb
System.Drawing.Common.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Drawing.Common.dll
System.Security.Permissions.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Security.Permissions.dll
System.Windows.Extensions.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Windows.Extensions.dll
YamlDotNet.dll -> E:\SteamLibrary\steamapps\common\Celeste\YamlDotNet.dll
linux -> E:\SteamLibrary\steamapps\common\Celeste\linux
osx -> E:\SteamLibrary\steamapps\common\Celeste\osx
win.x64.exe -> E:\SteamLibrary\steamapps\common\Celeste\win.x64.exe
win.x86.exe -> E:\SteamLibrary\steamapps\common\Celeste\win.x86.exe
FNA.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA.dll
FNA.pdb -> E:\SteamLibrary\steamapps\common\Celeste\FNA.pdb
FAudio.dll -> E:\SteamLibrary\steamapps\common\Celeste\FAudio.dll
FNA.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA.dll
FNA3D.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA3D.dll
SDL2.dll -> E:\SteamLibrary\steamapps\common\Celeste\SDL2.dll
libFAudio.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.so.0
libFNA3D.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.so.0
libSDL2-2.0.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.so.0
libtheorafile.so -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.so
libFAudio.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.0.dylib
libFNA3D.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.0.dylib
libMoltenVK.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libMoltenVK.dylib
libSDL2-2.0.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.0.dylib
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
libtheorafile.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dylib
libvulkan.1.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libvulkan.1.dylib
MoltenVK_icd.json -> E:\SteamLibrary\steamapps\common\Celeste\MoltenVK_icd.json
libdiscord_game_sdk.so -> E:\SteamLibrary\steamapps\common\Celeste\libdiscord_game_sdk.so
libFAudio.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.so.0
libFNA3D.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.so.0
libSDL2-2.0.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.so.0
libtheorafile.so -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.so
libdiscord_game_sdk.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libdiscord_game_sdk.dylib
libFAudio.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.0.dylib
libFNA3D.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.0.dylib
libMoltenVK.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libMoltenVK.dylib
libSDL2-2.0.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.0.dylib
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
libtheorafile.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dylib
libvulkan.1.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libvulkan.1.dylib
CSteamworks.dll -> E:\SteamLibrary\steamapps\common\Celeste\CSteamworks.dll
discord_game_sdk.dll -> E:\SteamLibrary\steamapps\common\Celeste\discord_game_sdk.dll
EULA-FMOD.txt -> E:\SteamLibrary\steamapps\common\Celeste\EULA-FMOD.txt
FAudio.dll -> E:\SteamLibrary\steamapps\common\Celeste\FAudio.dll
fmod64.dll -> E:\SteamLibrary\steamapps\common\Celeste\fmod64.dll
fmodstudio64.dll -> E:\SteamLibrary\steamapps\common\Celeste\fmodstudio64.dll
FNA3D.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA3D.dll
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
SDL2.dll -> E:\SteamLibrary\steamapps\common\Celeste\SDL2.dll
steam_api64.dll -> E:\SteamLibrary\steamapps\common\Celeste\steam_api64.dll
CSteamworks.dll -> E:\SteamLibrary\steamapps\common\Celeste\CSteamworks.dll
discord_game_sdk.dll -> E:\SteamLibrary\steamapps\common\Celeste\discord_game_sdk.dll
FAudio.dll -> E:\SteamLibrary\steamapps\common\Celeste\FAudio.dll
FNA3D.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA3D.dll
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
SDL2.dll -> E:\SteamLibrary\steamapps\common\Celeste\SDL2.dll
MoltenVK_icd.json -> E:\SteamLibrary\steamapps\common\Celeste\MoltenVK_icd.json
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
Info.plist -> E:\SteamLibrary\steamapps\common\Celeste\Info.plist
liblua54 -> E:\SteamLibrary\steamapps\common\Celeste\liblua54
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
Info.plist -> E:\SteamLibrary\steamapps\common\Celeste\Info.plist
liblua54 -> E:\SteamLibrary\steamapps\common\Celeste\liblua54
liblua54.dylib -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.dylib
Info.plist -> E:\SteamLibrary\steamapps\common\Celeste\Info.plist
liblua54 -> E:\SteamLibrary\steamapps\common\Celeste\liblua54
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
Microsoft.Win32.SystemEvents.dll -> E:\SteamLibrary\steamapps\common\Celeste\Microsoft.Win32.SystemEvents.dll
System.Drawing.Common.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Drawing.Common.dll
System.Windows.Extensions.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Windows.Extensions.dll

STEP: INSTALL
Starting MiniInstaller
Failed installing 4057 (core)
System.IO.FileNotFoundException: Não foi possível carregar arquivo ou assembly 'file:///E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.exe' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.
Nome do arquivo: 'file:///E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.exe'
   em System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   em System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   em System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   em System.Reflection.Assembly.LoadFrom(String assemblyFile)
   em MonoMod.Installer.Everest.EverestInfo.MiniInstallerProxy.Boot(MiniInstallerBridge bridge)
   em MonoMod.Installer.Everest.EverestInfo.MiniInstallerProxy.Boot(MiniInstallerBridge bridge)
   em MonoMod.Installer.Everest.EverestInfo.Install(Action`1 progress)
   em MonoMod.Installer.GameModder._Install()
   em MonoMod.Installer.GameModder.Install()

AVI: o log de associações de assembly está desativado.
Para ativar o log de  falhas de assembly, defina o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Observação: há alguma penalidade para o desempenho associada ao log de falha de associação de assembly.
Para desativar esse recurso, remova o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog].

Error! Please check installer-log.txt

**Comment by Kalobi** [comment]
Resolved on discord https://discord.com/channels/403698615446536203/1130918698287386747/1130918698287386747
