### ISSUE TITLE
The error about everest not being uninstalled correctly

### ISSUE THREAD

**Issue by lescatoo** [EverestAPI/Everest#646]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

English is not my mother tongue, I am using a translator to post questions, please understand, thank you
A long time ago, I installed the latest version of everest, but something went wrong at that time. During the installation process, I forcibly closed the installation program of everest, and then I could no longer install it

Windows prompts me four errors
--------------------------------------------
main.exe - corrupted image
C:Users\xtx52 AppData\Roaming Olympus\MSVCR120.dIl is not specified to run on Windows, or it contains errors. Please try reinstalling the program using the original installation media, or contact your system administrator or software vendor for support. Error status 0xc0000020.
--------------------------------------------
main.exe - broken image
C:Userslxtx52AppDataRoaming\Olympus\MSVCR120.dll is not specified to run on Windows, or it contains an error. Please try reinstalling the program using the original installation media, or contact your system administrator or software vendor for support. Error status 0xc0000020.
--------------------------------------------
main.exe - System Error
Code execution cannot continue because SDL2.dll was not found. Reinstalling the program might fix it
this problem.
--------------------------------------------
mainexe - broken image
C:Users\xtx52 AppData Roaming\Olympus\MSVCR120.dIl is not specified to run on Windows, or it contains errors. Please try reinstalling the program using the original installation media, or contact your system administrator or software vendor for support. Error status 0xc0000020.
----------------------OK------------------------
Then I tried to install the old version of everest, it was successfully installed, and it can be used perfectly

But I used to play games on the epic platform, and I bought Celeste on the steam platform during this summer promotion

When I installed celeste on steam, I chose the path of celeste on the epic platform. Steam didn’t download celeste, but directly read the game files, and then downloaded some small files, and then I could start playing celeste, but I entered the game, and my mod couldn’t be read. I don’t know why. Let me go to the log, I put the content of the log below, you can take a look, I don’t understand

I am very helpless now, if you can help me out, I am very grateful to you,

The inability to install the new version of everest may be caused by my forcibly closing the installed everest. The old version of everest may be caused by directly deleting the residual files under celeste. If possible, I want to use the latest version of everest. If there is no way, the old version is also available.

I think reinstalling the system can solve all problems, but it is very troublesome, there are many files on my computer, I have used it for many years

it bothers me

I ask for your help, thank you

### Steps to reproduce

-

### Expected behavior

-

### Operating System

win10

### Everest Version

4083(old)

### Additional context

installer-log

Everest.Installer v19.9.0.33802
Starting installation
Installing: 4083 (core)
To: E:\SteamLibrary\steamapps\common\Celeste
STEP: BACKUP @ E:\SteamLibrary\steamapps\common\Celeste
Celeste.exe -> orig\Celeste.exe

STEP: DOWNLOAD & UNPACK
Downloading https://dev.azure.com/EverestAPI/Everest/_apis/build/builds/3383/artifacts?artifactName=main&api-version=5.0&%24format=zip
0 bytes
Downloaded 33548.14 KiB in 12.16 seconds.
Celeste-icon.png -> E:\SteamLibrary\steamapps\common\Celeste\Celeste-icon.png
Celeste.Mod.mm.deps.json -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.deps.json
Celeste.Mod.mm.dll -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.dll
Celeste.Mod.mm.pdb -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.pdb
Celeste.Mod.mm.xml -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.Mod.mm.xml
Celeste.xml -> E:\SteamLibrary\steamapps\common\Celeste\Celeste.xml
DiscordGameSDK.dll -> E:\SteamLibrary\steamapps\common\Celeste\DiscordGameSDK.dll
DiscordGameSDK.pdb -> E:\SteamLibrary\steamapps\common\Celeste\DiscordGameSDK.pdb
DotNetZip.dll -> E:\SteamLibrary\steamapps\common\Celeste\DotNetZip.dll
FNA.xml -> E:\SteamLibrary\steamapps\common\Celeste\FNA.xml
I18N.CJK.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.CJK.dll
I18N.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.dll
I18N.MidEast.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.MidEast.dll
I18N.Other.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.Other.dll
I18N.Rare.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.Rare.dll
I18N.West.dll -> E:\SteamLibrary\steamapps\common\Celeste\I18N.West.dll
Jdenticon.dll -> E:\SteamLibrary\steamapps\common\Celeste\Jdenticon.dll
KeraLua.dll -> E:\SteamLibrary\steamapps\common\Celeste\KeraLua.dll
MAB.DotIgnore.dll -> E:\SteamLibrary\steamapps\common\Celeste\MAB.DotIgnore.dll
Microsoft.NET.HostModel.dll -> E:\SteamLibrary\steamapps\common\Celeste\Microsoft.NET.HostModel.dll
Microsoft.Win32.SystemEvents.dll -> E:\SteamLibrary\steamapps\common\Celeste\Microsoft.Win32.SystemEvents.dll
MiniInstaller-linux -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-linux
MiniInstaller-osx -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-osx
MiniInstaller-win.exe.manifest -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-win.exe.manifest
MiniInstaller-win.exe -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-win.exe
MiniInstaller-win64.exe -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller-win64.exe
MiniInstaller.deps.json -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.deps.json
MiniInstaller.dll -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.dll
MiniInstaller.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.pdb
MiniInstaller.runtimeconfig.json -> E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.runtimeconfig.json
Mono.Cecil.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.dll
Mono.Cecil.Mdb.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.Mdb.dll
Mono.Cecil.Pdb.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.Pdb.dll
Mono.Cecil.Rocks.dll -> E:\SteamLibrary\steamapps\common\Celeste\Mono.Cecil.Rocks.dll
MonoMod.Backports.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Backports.dll
MonoMod.Backports.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Backports.pdb
MonoMod.Backports.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Backports.xml
MonoMod.Core.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Core.dll
MonoMod.Core.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Core.pdb
MonoMod.Core.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Core.xml
MonoMod.Iced.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Iced.dll
MonoMod.Iced.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Iced.pdb
MonoMod.Iced.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Iced.xml
MonoMod.ILHelpers.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.ILHelpers.dll
MonoMod.ILHelpers.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.ILHelpers.pdb
MonoMod.Patcher.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.dll
MonoMod.Patcher.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.pdb
MonoMod.Patcher.runtimeconfig.json -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.runtimeconfig.json
MonoMod.Patcher.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher.xml
MonoMod.Patcher -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Patcher
MonoMod.RuntimeDetour.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.dll
MonoMod.RuntimeDetour.HookGen.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.dll
MonoMod.RuntimeDetour.HookGen.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.pdb
MonoMod.RuntimeDetour.HookGen.runtimeconfig.json -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.runtimeconfig.json
MonoMod.RuntimeDetour.HookGen.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen.xml
MonoMod.RuntimeDetour.HookGen -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.HookGen
MonoMod.RuntimeDetour.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.pdb
MonoMod.RuntimeDetour.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.xml
MonoMod.Utils.dll -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Utils.dll
MonoMod.Utils.pdb -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Utils.pdb
MonoMod.Utils.xml -> E:\SteamLibrary\steamapps\common\Celeste\MonoMod.Utils.xml
NETCoreifier.deps.json -> E:\SteamLibrary\steamapps\common\Celeste\NETCoreifier.deps.json
NETCoreifier.dll -> E:\SteamLibrary\steamapps\common\Celeste\NETCoreifier.dll
NETCoreifier.pdb -> E:\SteamLibrary\steamapps\common\Celeste\NETCoreifier.pdb
Newtonsoft.Json.dll -> E:\SteamLibrary\steamapps\common\Celeste\Newtonsoft.Json.dll
NLua.dll -> E:\SteamLibrary\steamapps\common\Celeste\NLua.dll
NLua.pdb -> E:\SteamLibrary\steamapps\common\Celeste\NLua.pdb
System.Drawing.Common.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Drawing.Common.dll
System.Security.Permissions.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Security.Permissions.dll
System.Windows.Extensions.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Windows.Extensions.dll
YamlDotNet.dll -> E:\SteamLibrary\steamapps\common\Celeste\YamlDotNet.dll
linux -> E:\SteamLibrary\steamapps\common\Celeste\linux
osx -> E:\SteamLibrary\steamapps\common\Celeste\osx
win.x64.exe -> E:\SteamLibrary\steamapps\common\Celeste\win.x64.exe
win.x86.exe -> E:\SteamLibrary\steamapps\common\Celeste\win.x86.exe
FNA.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA.dll
FNA.pdb -> E:\SteamLibrary\steamapps\common\Celeste\FNA.pdb
FAudio.dll -> E:\SteamLibrary\steamapps\common\Celeste\FAudio.dll
FNA.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA.dll
FNA3D.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA3D.dll
SDL2.dll -> E:\SteamLibrary\steamapps\common\Celeste\SDL2.dll
libFAudio.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.so.0
libFNA3D.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.so.0
libSDL2-2.0.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.so.0
libtheorafile.so -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.so
libFAudio.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.0.dylib
libFNA3D.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.0.dylib
libMoltenVK.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libMoltenVK.dylib
libSDL2-2.0.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.0.dylib
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
libtheorafile.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dylib
libvulkan.1.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libvulkan.1.dylib
MoltenVK_icd.json -> E:\SteamLibrary\steamapps\common\Celeste\MoltenVK_icd.json
libdiscord_game_sdk.so -> E:\SteamLibrary\steamapps\common\Celeste\libdiscord_game_sdk.so
libFAudio.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.so.0
libFNA3D.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.so.0
libSDL2-2.0.so.0 -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.so.0
libtheorafile.so -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.so
libdiscord_game_sdk.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libdiscord_game_sdk.dylib
libFAudio.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFAudio.0.dylib
libFNA3D.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libFNA3D.0.dylib
libMoltenVK.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libMoltenVK.dylib
libSDL2-2.0.0.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libSDL2-2.0.0.dylib
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
libtheorafile.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dylib
libvulkan.1.dylib -> E:\SteamLibrary\steamapps\common\Celeste\libvulkan.1.dylib
CSteamworks.dll -> E:\SteamLibrary\steamapps\common\Celeste\CSteamworks.dll
discord_game_sdk.dll -> E:\SteamLibrary\steamapps\common\Celeste\discord_game_sdk.dll
EULA-FMOD.txt -> E:\SteamLibrary\steamapps\common\Celeste\EULA-FMOD.txt
FAudio.dll -> E:\SteamLibrary\steamapps\common\Celeste\FAudio.dll
fmod64.dll -> E:\SteamLibrary\steamapps\common\Celeste\fmod64.dll
fmodstudio64.dll -> E:\SteamLibrary\steamapps\common\Celeste\fmodstudio64.dll
FNA3D.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA3D.dll
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
SDL2.dll -> E:\SteamLibrary\steamapps\common\Celeste\SDL2.dll
steam_api64.dll -> E:\SteamLibrary\steamapps\common\Celeste\steam_api64.dll
CSteamworks.dll -> E:\SteamLibrary\steamapps\common\Celeste\CSteamworks.dll
discord_game_sdk.dll -> E:\SteamLibrary\steamapps\common\Celeste\discord_game_sdk.dll
FAudio.dll -> E:\SteamLibrary\steamapps\common\Celeste\FAudio.dll
FNA3D.dll -> E:\SteamLibrary\steamapps\common\Celeste\FNA3D.dll
libtheorafile.dll -> E:\SteamLibrary\steamapps\common\Celeste\libtheorafile.dll
SDL2.dll -> E:\SteamLibrary\steamapps\common\Celeste\SDL2.dll
MoltenVK_icd.json -> E:\SteamLibrary\steamapps\common\Celeste\MoltenVK_icd.json
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
Info.plist -> E:\SteamLibrary\steamapps\common\Celeste\Info.plist
liblua54 -> E:\SteamLibrary\steamapps\common\Celeste\liblua54
liblua54.so -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.so
Info.plist -> E:\SteamLibrary\steamapps\common\Celeste\Info.plist
liblua54 -> E:\SteamLibrary\steamapps\common\Celeste\liblua54
liblua54.dylib -> E:\SteamLibrary\steamapps\common\Celeste\liblua54.dylib
Info.plist -> E:\SteamLibrary\steamapps\common\Celeste\Info.plist
liblua54 -> E:\SteamLibrary\steamapps\common\Celeste\liblua54
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
lua54.dll -> E:\SteamLibrary\steamapps\common\Celeste\lua54.dll
Microsoft.Win32.SystemEvents.dll -> E:\SteamLibrary\steamapps\common\Celeste\Microsoft.Win32.SystemEvents.dll
System.Drawing.Common.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Drawing.Common.dll
System.Windows.Extensions.dll -> E:\SteamLibrary\steamapps\common\Celeste\System.Windows.Extensions.dll

STEP: INSTALL
Starting MiniInstaller
Failed installing 4083 (core)
System.IO.FileNotFoundException: 未能加载文件或程序集“file:///E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.exe”或它的某一个依赖项。系统找不到指定的文件。
文件名:“file:///E:\SteamLibrary\steamapps\common\Celeste\MiniInstaller.exe”
   在 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   在 System.Reflection.Assembly.LoadFrom(String assemblyFile)
   在 MonoMod.Installer.Everest.EverestInfo.MiniInstallerProxy.Boot(MiniInstallerBridge bridge)
   在 MonoMod.Installer.Everest.EverestInfo.MiniInstallerProxy.Boot(MiniInstallerBridge bridge)
   在 MonoMod.Installer.Everest.EverestInfo.Install(Action`1 progress)
   在 MonoMod.Installer.GameModder._Install()
   在 MonoMod.Installer.GameModder.Install()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

Error! Please check installer-log.txt

**Comment by Kalobi** [comment]
Resolved on discord https://discord.com/channels/403698615446536203/1141250581168668672/1141250581168668672
