### ISSUE TITLE
Error installing Everest on Windows 10

### ISSUE THREAD

**Issue by Rainbowmon** [EverestAPI/Everest#65]
So, I decided to finally try out a few Celeste mods... But the Everest installer is giving me an error. Any chance someone could help me? Thanks in advance,

Rainbowmon of the Care-monic Spirits.

[miniinstaller-log.txt](https://github.com/EverestAPI/Everest/files/3854824/miniinstaller-log.txt)

**Comment by max4805** [comment]
> Unsupported version of Celeste: 1.2.6.1

Your Celeste is out-of-date, you should update it to be able to use Everest.

**Comment by Rainbowmon** [comment]
*facepalms* It's been so long since I used the PC version of Celeste (I usually play on the Nintendo Switch version), it completely slipped my mind that I hadn't gotten the Chapter 9 update. Oops! Thanks for the assist, Max!
