### ISSUE TITLE
Add option to close console with "open console" keybind

### ISSUE THREAD

**Issue by Dzhake** [EverestAPI/Everest#682]
### I am planning on implementing this myself

No

### Describe your request

Having console keybind is good, but now everest forces to use "esc" to close it. Option to allow keybind to close console too would be nice. I think i can do this myself, and i always wanted to contribute to everest, but if it takes two minutes to do (as i think), then maybe it would be easier to make for someone who has a lot of expirience with everest.

**Comment by Kalobi** [comment]
It's not that simple (see #679 ). Having customizable keyboard keys while also being able to type arbitrary characters in a console is just a fundamental conflict.

**Comment by Dzhake** [comment]
Based on #679 i guess best way is to add option which allows "`" to close console (i know, kinda jank, but i think this is best solution). Or you can make poll in #modding_updates about this ( 1 - keep as it's now, 2 - what i said just now, 3 - what DemoJameson said in #679 (last message))

**Comment by microlith57** [comment]
i'm not in favour of holding a poll just yet; i intend to investigate whether a customisable "close console" keybind is viable, and if so that would be the best solution

**Comment by Dzhake** [comment]
Ok, then i close this, because 1) 679 exists, literally same thing. 2) this is not something what as i understand can be done in near future.
