### ISSUE TITLE
Everest failed to install

### ISSUE THREAD

**Issue by Kingtheempire** [EverestAPI/Everest#72]
I'll just leave the install log here.
[installer-log.txt](https://github.com/EverestAPI/Everest/files/4006873/installer-log.txt)

**Comment by 0x0ade** [comment]
Are you sure you've installed the XNA Framework 4.0? Or are you using the
FNA version of Celeste?

Kingtheempire <notifications@github.com> schrieb am Sa., 28. Dez. 2019,
09:49:

**Comment by Kingtheempire** [comment]
Yeah, it seems that the problem was that I did not do the first-time setup. Thanks for the help!
