### ISSUE TITLE
Parent OptionSubMenu keeps focus when entering a child OptionSubMenu

### ISSUE THREAD

**Issue by ACherryJam** [EverestAPI/Everest#796]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

Parent OptionSubMenu keeps focus after entering a child OptionSubMenu, making user unable to interact with Option-based menu items using Left and Right inputs. Left/Right inputs trigger both child OptionSubMenu and Option item.

Menu structure example:
OptionSubMenu (Option A, Option B)
= OptionA: None
= OptionB: OptionSubMenu (Option C, Option D)
== OptionC: None
== OptionD: OnOff

Mod archive for replicating the issue is attached in additional context.

### Steps to reproduce

1. Open a menu with OptionSubMenu containing a object of Option<T> or its subclass nested inside another OptionSubMenu
2. Enter parent OptionSubMenu
3. Enter child OptionSubMenu
4. Press Left or Right
5. Both child OptionSubMenu and Option interacts

### Expected behavior

Child menu should be the only one keeping focus on Confirm input. Back input should return focus to parent menu.

### Operating System

Windows 10

### Everest Version

4896

### Additional context

Mod for replication: [ToggleablePauseMenuHiding.zip](https://github.com/user-attachments/files/16317594/ToggleablePauseMenuHiding.zip)

https://github.com/user-attachments/assets/699613f4-e1ac-4f73-aacd-54d60ca7ad3b

**Comment by RedFlames** [comment]
It looks like it's not a bug, it's just not a feature according to comment? Not that that changes much, besides "don't do this" :catplush:

![image](https://github.com/user-attachments/assets/8a574eba-8813-4afc-a2e9-1acea99c7684)

https://github.com/EverestAPI/Everest/blob/5c387ef0948dd4cf71ac5860900e817bdaaae166/Celeste.Mod.mm/Mod/UI/TextMenuExt.cs#L903-L908

**Comment by ACherryJam** [comment]
Oops, my fault for only reading decompiled code, should've checked the source code as well. My apologies for the unnecessary issue.
:catplush:
