### ISSUE TITLE
Fix the unresolved mod live code reloading bug

### ISSUE THREAD

**Issue by MikosDrafle** [EverestAPI/Everest#797]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

Ever since Everest 4818 came out, there has been a problem plaguing my (and others') development. Code Reloading is a feature implemented into Everest that allows you to reload assemblies on the spot whenever they are modified.
After this update, the feature simply got broken. It appears that the mod assembly just gets reloaded from the cached version and does not contain any new changes when building via Visual Studio (or any code editor in this case).

### Steps to reproduce

1. Launch your code mod in Visual Studio, or any code editor you use.
2. Have Celeste open.
3. Preferably add a filler line that isn't useful.
4. Build (Ctrl+B for Visual Studio).
5. The mod will get reloaded very quickly, as opposed to long waiting times at first. This proves that the mod is getting loaded from the cache.

### Expected behavior

The mod gets re-loaded directly from the file upon modification.

### Operating System

Windows 11 64-bit

### Everest Version

>4818

### Mods required to reproduce

Literally any code mod you own.

### Additional context

```
(07/22/2024 12:11:34) [Everest] [Info] [modasmctx] Reloading mod assembly context because of changed assembly: C:\Program Files (x86)\Steam\steamapps\common\Celeste\Mods\BlixelHelper\bin\BlixelHelper.dll
(07/22/2024 12:11:34) [Everest] [Info] [modasmctx] Reloading mod assembly context because of changed assembly: C:\Program Files (x86)\Steam\steamapps\common\Celeste\Mods\BlixelHelper\bin\BlixelHelper.dll
(07/22/2024 12:11:34) [Everest] [Info] [loader] Reloading mod assemblies: BlixelHelper
(07/22/2024 12:11:34) [Everest] [Info] [core] Unregistered code module Celeste.Mod.BlixelHelper.BlixelHelperModule for module BlixelHelper 1.1.2.
(07/22/2024 12:11:34) [Everest] [Info] [modasmctx] Loaded assembly BlixelHelper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from module 'BlixelHelper' path 'C:\Program Files (x86)\Steam\steamapps\common\Celeste\Mods\BlixelHelper\bin\BlixelHelper.dll'
(07/22/2024 12:11:34) [Everest] [Info] [core] Registered code module Celeste.Mod.BlixelHelper.BlixelHelperModule for module BlixelHelper 1.1.2.

```

The logs show the mod being loaded correctly, even though it's not being loaded from the file.

**Comment by SnipUndercover** [comment]
This is fixed as of the current beta/dev build, please update to them if you're using stable.
