### ISSUE TITLE
Things that still need acknowledged in StrawberryRegistry

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/Everest#83]
_uh-oh. I wasn't done._

But I'd like to take a little break and come back in a bit. I don't think anything I list here will be an API-breaking change.

- ~Non-tracked registered berries need to be tallied up too, so that save files can be gold-sleeved for levelsets that have all berries, tracked and secret, collected.~
  - ~A quick skim says we'll need to butcher OuiFileSelectSlot.cs pretty aggressively to do this...
    This is probably very low priority.~
  - ~Actually, Dadbod just suggested a save file indicator (a stamp, specifically) for "all collectibles".
    So maybe a golden ticket sleeve for every single berry in the levelset is a bit higher priority.~
  - The `completion_stamps` branch aims to tackle this.

- ~Do we need to do something to include registered modberries in `LevelData.excludeNames`? This looks a little suspicious and I should have looked into it earlier.~
  - ~Before I forget, it looks like I can just make one check for registered berries here. It's about making sure that IDs set for strawberries and certain checked objects never change.~
  - This is fixed now.

- ~Need to account for vanilla moonberries. (Ugh.)~
  - Turns out that was, like, a one-line fix. 🐬💦

- ~We may want a custom berry seed object that can accept an arbitrary Entity and double-checks that what is passed is a registered strawberry. Then we can read seed sprite data from custom berry definitions and do all the other things we need to with reflection.~
  - We have the GenericStrawberrySeed and its associated Cutscene that can accept GenericStrawberrySeeds.
  - I need to make a readability pass on both later, and an extensibility pass for at *least* the former. This means we'll be able to set certain variables externally, such as the sprite for the seed and how long the player has before the seed set is lost.
  - Actually, this means we could even let modders set custom rules for losing berry seeds!

- ~Non-vanilla berries aren't appearing in the Debug map. This is low priority, but we'll fix it anyway.~
  - We have debugging features! 🐬

Of course, feel free to tack on anything worth mentioning, or tackle something on here yourself.

**Comment by GreyMario** [comment]
That just leaves the Generic Strawberry Seed and cutscene. I'm still on the fence between going back to the original "change damn near every reference to Strawberry in it" plan and making a *really aggressive* pass on the generics for true genericization and to open up customization.

We should probably actually do the former

**Comment by bigkahuna443** [comment]
Resolved by #89 + some later cleanup
