### ISSUE TITLE
B-Sides don't appear.

### ISSUE THREAD

**Issue by tryobytee** [EverestAPI/Everest#850]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

Modded B-Sides don't seem to work with Everest 5095 (also 5090 haven't tried any other versions), however they work on stable 5052. I found this issue with Into the Jungle.

### Steps to reproduce

1. Install Everest 5095
2. Install Into the Jungle (or presumably other campaigns with B-Sides)
3. Unlock B-Sides
4. B-Sides won't show up when you try to open the chapter screen, if they were previously completed, you will have the Red Heart but stats such as deaths/time won't be available

### Expected behavior

B-Sides to show up.

### Operating System

PopOS 22.04/Linux

### Everest Version

5095

### Mods required to reproduce

Into the Jungle + Requirements per it's everest.yaml - https://gamebanana.com/mods/292719 

OR presumably any other campaign with B-Sides

### Additional context

Note: This issue started occuring for me several weeks ago and I went through process of elimination to check each dependency that has had an update in that timeframe and after checking each mod and downgrading Everest it was evident that Everest was the issue.

**Comment by AAA1459** [comment]
It seems that only the BC side of ITJ will not appear, and cannot find through debug or console, and everest-dev-5024 also has same problem

**Comment by maddie480** [comment]
wouldn't be surprising if the metadata change:tm: was to blame for this (#503 and the associated fixes that have been stuck on beta for months)

**Comment by maddie480** [comment]
the part of area data loading responsible for putting the B-side and C-side data "inside" the A-side data was apparently putting _the C-side inside of the B-side_ instead...
